### ISSUE TITLE
Can't import example script buyapple after installation with pip

### ISSUE THREAD

**Issue by xmcpam** [quantopian/zipline#2058] opened 2017-12-20 15:06 UTC
In a clean Debian 9.2 environment, I'can't import the buyapple example script. 
```
$ sudo docker run -it debian:9.2 /bin/bash
# What follows now happens within the docker container:
$ apt-get update
$ apt-get install python-pip
$ pip install zipline
$ pip install ipython
$ ipython

In [1]: from zipline.examples import buyapple
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-2ab9218fdf43> in <module>()
----> 1 from zipline.examples import buyapple

/usr/local/lib/python2.7/dist-packages/zipline/__init__.py in <module>()
     19 # it is a place to expose the public interfaces.
     20 from . import data
---> 21 from . import finance
     22 from . import gens
     23 from . import utils

/usr/local/lib/python2.7/dist-packages/zipline/finance/__init__.py in <module>()
     14 # limitations under the License.
     15
---> 16 from . import execution, trading
     17
     18 __all__ = [

/usr/local/lib/python2.7/dist-packages/zipline/finance/execution.py in <module>()
     20 from six import with_metaclass
     21
---> 22 import zipline.utils.math_utils as zp_math
     23
     24 from numpy import isfinite

/usr/local/lib/python2.7/dist-packages/zipline/utils/math_utils.py in <module>()
     51     # fast versions
     52     import bottleneck as bn
---> 53     nanmean = bn.nanmean
     54     nanstd = bn.nanstd
     55     nansum = bn.nansum

AttributeError: 'module' object has no attribute 'nanmean'
```

**Comment by freddiev4** [comment] 2017-12-22 04:34
Just out of curiosity, why are you trying to import the example, rather than running through the CLI with `zipline run`?

**Comment by richafrank** [comment] 2017-12-22 14:34
FWIW That error typically means that `bottleneck` was not pip installed successfully. Have you tried pip uninstalling it, and then `pip install bottleneck==1.0.0 --no-binary bottleneck`? Often the cause of the failure is that its binary components were compiled against a different version of numpy than is currently installed.

**Comment by ernestoeperez88** [comment] 2020-01-14 16:36
@xmcpam I'm gonna go ahead and close this issue. Please feel free to reopen if you run into any other issues.

**Closed by ernestoeperez88** 2020-01-14 16:36 UTC
Labels: Install Help
