### ISSUE TITLE
get_trading_days doesn't return Friday trading day in tight range

### ISSUE THREAD

**Issue by jikamens** [quantopian/zipline#243] opened 2013-12-03 20:14 UTC
If you pass get_trading_days a time range that includes exactly a Friday, it doesn't return it in the result:

```
(Pdb) get_trading_days(datetime.datetime(2013,11,22,5,0,0,tzinfo=pytz.utc), datetime.datetime(2013,11,23,4,59,59,tzinfo=pytz.utc))
Index([], dtype=object)
```

Shift both times exactly a day earlier, and it works just fine:

```
(Pdb) get_trading_days(datetime.datetime(2013,11,21,5,0,0,tzinfo=pytz.utc), datetime.datetime(2013,11,22,4,59,59,tzinfo=pytz.utc))
<class 'pandas.tseries.index.DatetimeIndex'>
[2013-11-21 05:00:00]
Length: 1, Freq: None, Timezone: UTC
```

It also works the day before a non-trading-day that is a holiday rather than a Saturday, so this appears to be somehow unique to how weekends are handled:

```
(Pdb) get_trading_days(datetime.datetime(2013,11,27,5,0,0,tzinfo=pytz.utc), datetime.datetime(2013,11,28,4,59,59,tzinfo=pytz.utc))
<class 'pandas.tseries.index.DatetimeIndex'>
[2013-11-27 05:00:00]
Length: 1, Freq: None, Timezone: UTC
```

**Comment by richafrank** [comment] 2017-11-21 14:47
Whatever the cause, looks like on the latest version of zipline (and pandas 0.18.1), these all return more values than you were seeing:
```
In [10]: get_trading_days(datetime.datetime(2013,11,22,5,0,0,tzinfo=pytz.utc), datetime.datetime(2013,11,23,4,59,59,tzinfo=pytz.utc))
Out[10]: DatetimeIndex(['2013-11-22'], dtype='datetime64[ns, UTC]', freq='C')

In [11]: get_trading_days(datetime.datetime(2013,11,21,5,0,0,tzinfo=pytz.utc), datetime.datetime(2013,11,22,4,59,59,tzinfo=pytz.utc))
Out[11]: DatetimeIndex(['2013-11-21', '2013-11-22'], dtype='datetime64[ns, UTC]', freq='C')

In [12]: get_trading_days(datetime.datetime(2013,11,27,5,0,0,tzinfo=pytz.utc), datetime.datetime(2013,11,28,4,59,59,tzinfo=pytz.utc))
Out[12]: DatetimeIndex(['2013-11-27'], dtype='datetime64[ns, UTC]', freq='C')
```

I'm going to close this. Feel free to reopen if there's a workflow this is breaking.

**Closed by richafrank** 2017-11-21 14:47 UTC
