### ISSUE TITLE
Quandl data feed update: WIKI stock prices - NO LONGER UPDATING as of April 11, 2018

### ISSUE THREAD

**Issue by yiorgosn** [quantopian/zipline#2145] opened 2018-04-13 14:25 UTC
Received this from Quandl Support April 11, 2018:

I'm emailing you because you've downloaded US stock price data from the WIKI data feed in the past.

As you know, WIKI is a community-maintained data feed based on public sources. Unfortunately, one of the main sources of that data is no longer available, and our community volunteers have been unable to find a suitable alternative source.

As a result, the WIKI data feed is likely to be a lot less reliable in the future, with potentially missing or incorrect data or delayed updates.

We will continue to host this data feed on Quandl, but we no longer recommend using it for investment or analysis.

Unfortunately, we don't have any free stock price data feeds that can replace WIKI at this time. The closest alternative we have is EOD, which is a value-priced end-of-day US stock price data feed.

Thank you for your understanding.

**Comment by freddiev4** [comment] 2018-04-13 14:57
Hi @yiorgosn. I also received this email the other day 🙂 thanks for opening an issue to track this.

**Comment by yiorgosn** [comment] 2018-04-13 15:53
Just to clarify the zipline ingest will still download  a 250MB file with all historical data from 1996 until March 27, 2018.  So for academic purposes that don't need data updated as of last night it still works and Quandl may periodically update it also.

**Comment by wuliang727** [comment] 2019-02-13 02:43
Still no update of wiki price since 2018-03-28. I just wonder what other api you guys use for finance, such as end-of-day stock price?

**Comment by fawce** [comment] 2019-12-31 16:30
marking as dupe of https://github.com/quantopian/zipline/issues/2603

**Closed by fawce** 2019-12-31 16:30 UTC
Labels: Data Bundle
