### ISSUE TITLE
AttributeError: 'module' object has no attribute 'nanmean' when importing zipline

### ISSUE THREAD

**Issue by madawei2699** [quantopian/zipline#997] opened 2016-02-16 10:51 UTC
When I use virtualenv install zipline and I start python, but occure an error:
"AttributeError: 'module' object has no attribute 'nanmean' when importing zipline"
and I try solve the problem by using this issue: https://github.com/quantopian/zipline/issues/967 . My problem is same with this post, this problem should solved by @richafrank ,but my problem is not solved.I reinstall zipline with this command: pip install git+https://github.com/quantopian/zipline.git and the problem is not solved.

**Comment by madawei2699** [comment] 2016-02-16 12:11
I fix this problem by using follow step:
`pip uninstall bottleneck`
After I unistall bottleneck, python import print an error saying numpy library version error. So I upgrade numpy by:
`easy_install --upgrade numpy`
and the numpy version now is 1.11.0b3
the problem is solved. Now my zipline version is v0.8.3+322.gd5bd2a9

**Comment by richafrank** [comment] 2016-02-16 17:24
Forgetting zipline for a moment, are you able to `pip install bottleneck` in a new virtualenv and `from bottleneck import nanmean`?

**Comment by madawei2699** [comment] 2016-02-16 17:30
I can install bottleneck by pip in a new virtualenv, but cannot execute `from bottleneck import nanmean` which print bottleneck has no attribute nanmean. I fix this problem by uninstall bottleneck and upgrade numpy to lastest version.Maybe the problem is relate to numpy version.
Now I can import zipline without error.

**Comment by richafrank** [comment] 2016-02-16 22:18
The AttributeError from bottleneck occurs when its C extensions fail to import.  Is it possible you installed zipline 0.8.3, which downgrades numpy to 1.9.2, after having installed bottleneck with numpy 1.10?  (zipline master no longer does this, and we're working to release to PyPI/anaconda.)

**Comment by madawei2699** [comment] 2016-02-17 04:31
I just install zipline by `pip install zipline` and the version is 0.8.3. Then the AttributeError occured. The pip is lastest version and the dependence controlled by pip. The reason maybe is liked that you said.

**Comment by llllllllll** [comment] 2016-02-23 22:46
Can you try to install zipline master in a new virtualenv to see if this resolves your issue?

**Comment by richafrank** [comment] 2016-03-30 14:44
The numpy downgrade should have been fixed in zipline 0.8.4.  Closing, but feel free to re-open if there's still an issue.

**Closed by richafrank** 2016-03-30 14:44 UTC
Labels: Packaging

**Comment by bicepjai** [comment] 2016-05-19 03:27
I have zipline==0.9.0 and still get the same issue when i execute buyapple.py script.

**Comment by richafrank** [comment] 2016-05-19 17:21
Hi @bicepjai , did you try re-installing or uninstalling bottleneck?  

This is caused by bottleneck running with a different version of numpy from the one that it was compiled against.  You'd need to make sure you're not using a cached wheel.  Alternatively, you could uninstall bottleneck altogether, since it's an optional dependency of zipline.

**Comment by bicepjai** [comment] 2016-05-20 01:02
it worked after clean install

**Comment by yash486gadhavi** [comment] 2018-03-14 08:26
If you are using anaconda jupyter notebook., then you just have to install the bottelneck with the help of "conda install bottleneck" and  install zipline using "conda install -c quantopian zipline "  the bottleneck version error will be solved.
