### ISSUE TITLE
Pandas requirement out of date

### ISSUE THREAD

**Issue by dartdog** [quantopian/zipline#1870] opened 2017-07-01 15:26 UTC
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment
Conda py3.6

* Operating System: (Windows Version or `$ uname --all`) Ubuntu 16.04
* Python Version: `$ python --version`3.6
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`) Pip master into a condae nv with pyfolio maser
* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
Zipline down graded a number of packages including pandas from 20.2 to 18.. this prevents pyfolio from running,, so upgrading back to pandas 20.2 exposes no more pandas tslib.. it is gone so
an attempt to run from the example ipynb gives 

```
%matplotlib inline
%load_ext zipline
/home/tom/anaconda3/envs/pyfolioenv/lib/python3.6/site-packages/zipline/utils/calendars/exchange_calendar_ice.py:10: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import Timestamp
```
Followed by:

```---> 19 from pandas.tslib import normalize_date
     20 from six import string_types
     21 from sqlalchemy import create_engine

ImportError: cannot import name 'normalize_date'
```
* What did you expect to happen?
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by FreddieV4** [comment] 2017-07-03 17:38
Hi @dartdog thanks for posting your issue. So there's a few things going on here:

- Zipline does indeed require pandas `0.18`, so upgrading to a newer version of pandas will not fix the issue as we don't yet support the newer version of pandas in zipline.
- We don't support Python 3.6 for zipline so there may be issues from you running Python 3.6 as well

I suggest that you use zipline in a separate virtualenv from pyfolio if you want to use both of them.

**Comment by Jfeng3** [comment] 2017-09-13 19:30
@FreddieV4 Hi FreddieV4, I am trying to use zipline with pyforlio.
 you suggest here "use zipline in a separate virtualenv from pyfolio if you want to use both of them." 

Do you mean I need to switch between virtualenvs when I run code with both pyfolio and zipline?

**Comment by richafrank** [comment] 2017-09-18 14:33
xref https://github.com/quantopian/pyfolio/issues/407

**Comment by abhijeetkalyan** [comment] 2017-09-18 14:35
Hi @Jfeng3 - as of now, you'll need to do that, because they don't currently work in the same virtual env. This is on our radar to fix in the short term.

**Comment by aking7** [comment] 2017-11-18 19:05
Any news on this? It's a shame they don't work together.

**Comment by richafrank** [comment] 2017-11-20 19:12
Hi @aking7 , I believe pyfolio is compatible with pandas 0.18 again! Have you tried installing pyfolio from github to get the latest?

@twiecki Shall we cut a pyfolio release?

**Comment by aking7** [comment] 2017-11-20 19:25
@richafrank I'm more interested in getting zipline up to date with the current pandas as I'm using some of its features.

**Comment by twiecki** [comment] 2017-11-20 19:30
@richafrank Definitely, should cut a new release.

**Comment by richafrank** [comment] 2017-11-20 19:40
@aking7 Ah, ok. I believe that was in progress [here](https://github.com/quantopian/zipline/pull/1975), but has been dormant for a bit. If you want to get a PR into a good state for the version you need, we can help shepherd it through.

**Comment by imkoukou** [comment] 2017-12-21 17:23
Any progress on the new pandas (current 0.21.1)??

**Comment by richafrank** [comment] 2017-12-21 17:53
@imkoukou I'm not aware of any work done on zipline to support the latest pandas. PRs welcome!

**Comment by lalas** [comment] 2017-12-31 00:07
So is there a way to reproduce the example found at
https://github.com/quantopian/research_public/blob/master/blog/bayes_opt/Blog_Post_Zipline_SigOpt.ipynb

If so, which version of pandas, zipline and pyfolio packages should one maintain in an environment?

**Comment by Yevgnen** [comment] 2018-01-31 07:05
Any news?

**Comment by ahmad-emanuel** [comment] 2018-01-31 18:03
I expected at least a simple warning:
"Do not install the both together"
I must nun reinstall my zipline environment, after a few hours Search for reason of Issue

**Comment by h55nick** [comment] 2018-02-22 01:45
Just ran into this and using the docker setup so using different virtualenvs gets pretty meta in my situation. Though admittedly I haven't tried setting up a 2x virualenvs within the docker containers. could be a fun experiment...

In general finding, the dependency tangles pretty gnarly. I wanted to update sklearn (cool new preprocessors!) and now wondering down a multi-day journey of reconfiguring my environment.

**Comment by ralirah27** [comment] 2018-06-24 04:33
Hi. I'm Japanese boy.
I want to use it in google colaboratory, but I am suffering from this problem.
How many versions of pandas should I downgrade?

**Comment by richafrank** [comment] 2018-07-19 15:47
Closing - See https://github.com/quantopian/zipline/pull/2194 and https://github.com/quantopian/zipline/issues/2243

**Closed by richafrank** 2018-07-19 15:47 UTC
Labels: Install Help, Python 3.6
