### ISSUE TITLE
OTC assets not fetched in quandl bundle

### ISSUE THREAD

**Issue by AhmMontasser** [quantopian/zipline#2602] opened 2019-12-28 15:34 UTC
Hello, 

I ingested quandl data bundle in zipline using the normal methods described in the docs. 
QUANDL_API_KEY=<yourkey> zipline ingest -b quandl

My problem is that I am trying to read some of the OTC assets but they are not found. 

for example, current asset list [CFST,BKSC,ABNK,CNAF,FSEA,BCTF,NIDB,HVBC,MELR,MVLY,EQFN,CYFL,FSBC,CFBI,OTTW,FFBW,CBMB,MSVB,CIZN] gives me not found when i use symbol() function to fetch the equity object of any of them. 

what should i do to include all bundle that i subscribed on quandl ? 

note, I have a paid subscription including that set of assets.

Regards,

**Comment by ernestoeperez88** [comment] 2020-01-17 21:18
Hi @AhmMontasser . The data bundle created by running `QUANDL_API_KEY= zipline ingest -b quandl` uses quandl's free WIKI dataset, which I believe doesn't include the assets you are looking for.

In order to ingest a dataset for which you have a quandl subscription, you will need to create a zipline data bundle specific to that dataset. Chances are it will have a structure similar to zipline's [quandl bundle](https://github.com/quantopian/zipline/blob/master/zipline/data/bundles/quandl.py), you would only need to tailor it to your specific dataset.

**Comment by ssanderson** [comment] 2020-03-10 14:48
Closing this as a dupe of https://github.com/quantopian/zipline/issues/2603. The upstream data source used to create the quandl bundle is no longer maintained by Quandl, so it's unlikely there's anything that can be done about this.

**Closed by ssanderson** 2020-03-10 14:48 UTC
Labels: Data Bundle
