### ISSUE TITLE
Test test_perf_tracking.py 

### ISSUE THREAD

**Issue by fysdbd** [quantopian/zipline#1641] opened 2017-01-08 09:06 UTC
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Linux ubuntu 4.8.6-x86_64-linode78 #1 SMP Tue Nov 1 14:51:21 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: Python 2.7.6
* Python Bitness: 64
* How did you install Zipline: cloned from github
* Python packages:
alabaster==0.7.6
alembic==0.7.7
AlgoTrading==0.2.2
apt-xapian-index==0.45
Babel==1.3
backports-abc==0.5
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.4.0.2
bcolz==0.12.1
beautifulsoup4==4.2.1
blaze==0.10.1
boto==2.20.1
Bottleneck==1.2.0
certifi==2015.4.28
chardet==2.0.1
click==4.0
cloudpickle==0.2.2
colorama==0.2.5
conda==4.2.7
configparser==3.5.0
contextlib2==0.4.0
cookies==2.2.1
coverage==4.0.3
cvxopt==1.1.4
cycler==0.10.0
cyordereddict==0.2.2
Cython==0.25.2
dask==0.13.0
DataAPI==0.8.2
datashape==0.5.2
decorator==4.0.0
Django==1.6.1
docopt==0.6.2
docutils==0.12
empyrical==0.2.1
entrypoints==0.2.2
enum34==1.1.6
Finance-Python==0.4.3
flake8==2.4.1
Flask==0.12
Flask-Cors==3.0.2
funcsigs==0.4
functools32==3.2.3.post2
futures==3.0.5
gevent==1.2.0
greenlet==0.4.11
guppy==0.1.9
h5py==2.6.0
HelloWorld==0.1
html5lib==0.999
http==0.2
httplib2==0.8
ImageHash==3.1
intervaltree==2.1.0
iotop==0.6
ipykernel==4.5.2
ipython==5.1.0
ipython-genutils==0.1.0
ipywidgets==5.2.2
itsdangerous==0.24
Jinja2==2.7.3
joblib==0.7.1
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.4.0
jupyter-console==5.0.0
jupyter-core==4.2.1
Keras==1.1.2
latexcodec==1.0.4
locket==0.2.0
Logbook==0.12.5
lru-dict==1.1.4
lxml==3.7.1
Mako==1.0.6
Markdown==2.6.2
MarkupSafe==0.23
matplotlib==1.4.3
mccabe==0.3.1
mistune==0.7
mock==1.3.0
mongoengine==0.11.0
multipledispatch==0.4.8
MySQL-python==1.2.3
nbconvert==4.2.0
nbformat==4.2.0
networkx==1.9.1
nose==1.3.7
nose-ignore-docstring==0.2
nose-parameterized==0.5.0
nose-timer==0.5.0
notebook==4.2.3
numexpr==2.6.1
numpy==1.11.3
numpydoc==0.5
odo==0.5.0
openpyxl==1.7.0
oset==0.1.3
PAM==0.4.2
pandas==0.18.1
pandas-datareader==0.2.1
partd==0.3.7
pathlib2==2.1.0
patsy==0.4.0
pbr==1.3.0
pep8==1.5.7
pexpect==3.1
pickleshare==0.7.4
Pillow==2.3.0
piprot==0.9.6
plotly==1.12.9
prompt-toolkit==1.0.9
psutil==5.0.0
ptyprocess==0.5.1
pyandoc==0.0.1
pyasn1==0.1.7
pybtex==0.20.1
pybtex-docutils==0.2.1
pycrypto==2.6.1
pycurl==7.19.3
pyflakes==0.8.1
Pygments==2.0.2
pygobject==3.12.0
pymongo==3.4.0
pymssql==2.1.3
pyOpenSSL==0.13
pyparsing==2.0.3
pyqtgraph==0.10.0
pyserial==2.6
python-apt===0.9.3.5ubuntu2
python-dateutil==2.4.2
python-debian===0.1.21-nmu2ubuntu2
pytz==2016.4
PyWavelets==0.5.1
pyxdg==0.25
PyYAML==3.12
pyzmq==14.0.1
qtconsole==4.2.1
redis==2.10.5
requests==2.9.1
requests-file==1.4.1
requests-futures==0.9.7
responses==0.4.0
roman==2.0.0
scikit-learn==0.18.1
scipy==0.17.1
seaborn==0.7.1
simplegeneric==0.8.1
simplejson==3.3.1
singledispatch==3.4.0.3
six==1.10.0
sklearn==0.0
snowballstemmer==1.2.0
sortedcontainers==1.4.4
Sphinx==1.3.4
sphinx-rtd-theme==0.1.8
sphinxcontrib-bibtex==0.3.4
SQLAlchemy==1.0.8
ssh-import-id==3.21
statsmodels==0.6.1
subprocess32==3.2.7
sympy==0.7.4.1
TA-Lib==0.4.8
tables==3.3.0
termcolor==1.1.0
terminado==0.6
testfixtures==4.1.2
Theano==0.8.2
toolz==0.7.4
tornado==4.2.1
traitlets==4.3.1
tushare==0.5.8
Twisted-Conch==13.2.0
Twisted-Core==13.2.0
Twisted-Mail==13.2.0
Twisted-Names==13.2.0
Twisted-Web==13.2.0
urllib3==1.7.1
urwid==1.1.1
virtualenv==1.11.4
VisualPortfolio==0.2.2
w3lib==1.5
wcwidth==0.1.7
Werkzeug==0.11.15
wget==3.2
widgetsnbextension==1.2.6
xlrd==0.9.4
xlwt==0.7.5
zipline==1.0.2+368.g9f60524
zope.interface==4.0.5

Now that you know a little about me, let me tell you about the issue I am
having:

I try to run test cases using nosetests. Everything is fine here but one:
tests/test_perf_tracking.py
Almost all cases in this suite shows similar problem, and I have pasted some of them in the following:

> Traceback (most recent call last):
  File "/home/fysdbd/zipline/tests/test_perf_tracking.py", line 792, in test_ending_before_pay_date
    writer.write(splits, mergers, dividends)
  File "/home/fysdbd/zipline/zipline/data/us_equity_pricing.py", line 1171, in write
    self.write_dividend_data(dividends, stock_dividends)
  File "/home/fysdbd/zipline/zipline/data/us_equity_pricing.py", line 1079, in write_dividend_data
    self._write_dividends(dividends)
  File "/home/fysdbd/zipline/zipline/data/us_equity_pricing.py", line 1052, in _write_dividends
    self.write_dividend_payouts(dividend_payouts)
  File "/home/fysdbd/zipline/zipline/data/us_equity_pricing.py", line 941, in write_dividend_payouts
    frame,
  File "/home/fysdbd/zipline/zipline/data/us_equity_pricing.py", line 891, in _write
    frame.columns.tolist(),
ValueError: Unexpected frame columns:
Expected Columns: set(['declared_date', 'amount', 'pay_date', 'sid', 'ex_date', 'record_date'])
Received Columns: ['amount', 'declared_date', 'ex_date', 'pay_date', 'record_date', 'sid']

> Traceback (most recent call last):
  File "/home/fysdbd/zipline/tests/test_perf_tracking.py", line 598, in test_long_position_purchased_on_ex_date_receives_no_dividend
    writer.write(splits, mergers, dividends)
  File "/home/fysdbd/zipline/zipline/data/us_equity_pricing.py", line 1171, in write
    self.write_dividend_data(dividends, stock_dividends)
  File "/home/fysdbd/zipline/zipline/data/us_equity_pricing.py", line 1079, in write_dividend_data
    self._write_dividends(dividends)
  File "/home/fysdbd/zipline/zipline/data/us_equity_pricing.py", line 1052, in _write_dividends
    self.write_dividend_payouts(dividend_payouts)
  File "/home/fysdbd/zipline/zipline/data/us_equity_pricing.py", line 941, in write_dividend_payouts
    frame,
  File "/home/fysdbd/zipline/zipline/data/us_equity_pricing.py", line 891, in _write
    frame.columns.tolist(),
ValueError: Unexpected frame columns:
Expected Columns: set(['declared_date', 'amount', 'pay_date', 'sid', 'ex_date', 'record_date'])
Received Columns: ['amount', 'declared_date', 'ex_date', 'pay_date', 'record_date', 'sid']

I have tried looking into the issue and the exception was raised around zipline/data/us_equity_pricing.py line 885, when
`fronzenset(frame.columns) != viewkeys(expected_dtypes)`
return true

The contents/values in the frame columns and expected_dtypes do match though; however it seems in my current setup, fronzenset and dict_keys (returned by viewkeys) are not recognised to be the same, i.e. 
>  fysdbd@ubuntu:~/zipline$ python -c "a = frozenset([1,2,3]); from six import viewkeys; b = viewkeys({2:2,1:1,3:3}); print a != b"
True

Additionally as a simple test, I tried changing viewkeys to set:
`fronzenset(frame.columns) != set(expected_dtypes)`
and the test case passed successfully.

Not sure whether it is my setup/version issue, or we need to do some little change here.

Sincerely,
Daniel Xu

**Comment by FreddieV4** [comment] 2017-03-23 05:54
Hey @fysdbd are you still seeing this issue? I'm not able to reproduce it on zipline master

**Comment by freddiev4** [comment] 2017-12-02 19:47
Fixed by #1954

**Closed by freddiev4** 2017-12-02 19:47 UTC
Labels: Bug, Testing
