### ISSUE TITLE
Make zipline Pandas >= 0.20 compatible 

### ISSUE THREAD

**Issue by twiecki** [quantopian/zipline#1994] opened 2017-10-25 09:48 UTC
Currently Zipline requires pandas 0.18.1 which is quite outdated and incompatible with many other current versions of other packages. As such, having zipline installed in your environment makes things very difficult. Would be great to update the requirement to a current version.

**Comment by richafrank** [comment] 2017-10-25 13:11
Thanks @twiecki . I'm going to close this as a duplicate of #1870, but I agree with the issue. 

cc @abhijeetkalyan

**Closed by richafrank** 2017-10-25 13:11 UTC
