### ISSUE TITLE
try to run the examples with anaconda 32bit on win8 64bit, but all examples point to this error

### ISSUE THREAD

**Issue by mickeydonkey** [quantopian/zipline#804] opened 2015-10-31 06:31 UTC
take the buyapple.py as an example:
```python
runfile('D:/git_download/zipline/zipline/examples/buyapple.py', wdir='D:/git_download/zipline/zipline/examples')
AAPL
Traceback (most recent call last):

  File "<ipython-input-1-35d94a5df363>", line 1, in <module>
    runfile('D:/git_download/zipline/zipline/examples/buyapple.py', wdir='D:/git_download/zipline/zipline/examples')

  File "d:\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 685, in runfile
    execfile(filename, namespace)

  File "d:\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 85, in execfile
    exec(compile(open(filename, 'rb').read(), filename, 'exec'), namespace)

  File "D:/git_download/zipline/zipline/examples/buyapple.py", line 65, in <module>
    identifiers=['AAPL'])

  File "d:\Anaconda3\lib\site-packages\zipline-0.8.0rc1-py3.4-win32.egg\zipline\algorithm.py", line 211, in __init__
    futures_data=kwargs.pop('futures_metadata', {}),

  File "d:\Anaconda3\lib\site-packages\zipline-0.8.0rc1-py3.4-win32.egg\zipline\finance\trading.py", line 194, in write_data
    allow_sid_assignment=allow_sid_assignment)

  File "d:\Anaconda3\lib\site-packages\zipline-0.8.0rc1-py3.4-win32.egg\zipline\finance\trading.py", line 199, in _write_data_lists
    .write_all(self.engine, allow_sid_assignment=allow_sid_assignment)

  File "d:\Anaconda3\lib\site-packages\zipline-0.8.0rc1-py3.4-win32.egg\zipline\assets\asset_writer.py", line 231, in write_all
    data = self.load_data()

  File "d:\Anaconda3\lib\site-packages\zipline-0.8.0rc1-py3.4-win32.egg\zipline\assets\asset_writer.py", line 426, in load_data
    self.dt_to_epoch_ns(equities_output[date_col])

  File "d:\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2127, in __setitem__
    self._set_item(key, value)

  File "d:\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2204, in _set_item
    value = self._sanitize_column(key, value)

  File "d:\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2362, in _sanitize_column
    value = _sanitize_index(value, self.index, copy=False)

  File "d:\Anaconda3\lib\site-packages\pandas\core\series.py", line 2579, in _sanitize_index
    raise ValueError('Length of values does not match length of '

ValueError: Length of values does not match length of index
```

**Comment by mickeydonkey** [comment] 2015-10-31 06:44
I download current master branch and use setup.py to install zipline 0.8.0rc1

**Comment by AnthonyFJGarner** [comment] 2015-10-31 09:18
I have had similar problems.One day I was happily using zipline with anaconda 32bit on Windows 10. After a pull and the necessity to upgrade Toolz, I have been having exactly the same problem as you ever since. I have meticulously loaded the correct versions of each dependency so that installing zipline in development mode goes without error or the need to downgrade any of the dependencies by zipline setup.py

Despite spending 10 days installing, deleting and reinstalling ziplne, anaconda and every individual dependency I always end up with the same error as you have come across.

I have also tried anaconda 64 bit but am unable to overcome errors with the C compiler when building various dependencies such as logbook which rely on disutils:

```
File "C:\Anaconda\lib\site-packages\setuptools-18.4-py3.4.egg\setuptools\msvc9_support.py", line 52, in query_vcvarsall
      File "C:\Anaconda\lib\distutils\msvc9compiler.py", line 287, in query_vcvarsall
        raise ValueError(str(list(result.keys())))
    ValueError: ['path']
```
Very, very dispiriting indeed.
I have loaded Visual C++ 2010, Visual Sudio 2015 (specifically including C++), and Microsoft Visual C++ Compiler for Python 2.7.

Others have made the 64 bit version work. I can't.

Working with Zipline has so far proved an extremely dispiriting waste of time. Sadly.

**Comment by mickeydonkey** [comment] 2015-10-31 10:22
@AnthonyFJGarner ,we have quite similar misfortune. During this week, I have installed virtual studio 2015, 2010 and 2008, as well as different versions of anaconda. I succeeded installing zipline for 64bit anaconda, but ended up with the same error message as the one I post in this issue. I doubt the master branch is not for newbie programmers. I suggest you using the stable zipline 0.7.0 as workround, it works.

**Comment by AnthonyFJGarner** [comment] 2015-10-31 11:48
No. It is useless. You will find many features are missing. Hopeless.

**Comment by Zigguratti** [comment] 2015-10-31 12:09
I had this joy too.  In the end, I installed ubuntu as I need 64 bit due to
memory constraints; the final straw was anaconda 32bit zipline breaking.  I
really think they don't bother to support windows.  Running ubuntu under a
virtual machine is fine for now at any rate.  Also, pyfolio doesn't seem to
install under python 3.3 .  Why support 2.7 and not 3+? Although 2.7 may
have libraries that are not yet in 3, 3 is the future.  I gather I may just
have to build a local version for 3, but if its that easy (for a techy)
then why not just do it for me?  Great product, but support is stretched.
The message, to me, really is, move to linux if you want to use zipline.
And ideally 2.7, which seems bonkers (!).  A friend works at Docker,
apparently that precisely solves these sorts of problems.  Somewhere on my
to-do list!

**Comment by Zigguratti** [comment] 2015-10-31 12:13
(not wishing to sound too negative.  Zipline is very exciting.  It is also
a bit slow, I gather there is an optimization hack, the sooner that gets
implemented, the better! I am new to python/ubuntu/github, so its a bit of
a learning curve for a n00b, and might be made simpler.  There are plenty
of people who code and do quant maths who aren't and never will be software
devs who don't really need to know/learn all this stuff! too much else to
learn/do!)

**Comment by AnthonyFJGarner** [comment] 2015-10-31 12:29
Hi Carl. Good to hear from you again. I was also thinking of moving to
Linux. One problem is that our data source relies on a Windows only
program. The problem with this whole Zipline game is the ever changing list
of dependencies and versions. Take anaconda 32 bit. It has an old version
of Pip. Which you have to update in order to install Zipline is development
mode. The you discover the new Pip with Wheels won't install Logbook and
some of the other dependencies. So you have to revert to the old version
and so on. And then when you finally have it all set up..

Bingo.....you are back to the problem described above.

Fine if you are a professional IT guy I expect. But hopeless otherwise.

**Comment by Zigguratti** [comment] 2015-10-31 13:33
Hi Anthony,

yes, this is a big problem in general I believe, hence Docker already being
a 'unicorn' SV company!

What is your software/data source?  the easiest way would be to dump the
data to csv and then read it in linux under a VM but I'm sure you have
thought of all that.

**Comment by AnthonyFJGarner** [comment] 2015-10-31 15:07
God knows. I spent many hours using Pycharm and its debugger going line by line through the buyapple.py example and through every call to zipline components and pandas/numpy/python.....but ended up not being able to pin this error down.

Perhaps I'll try Linux...there again...have I got the time and energy. There is SO much that still needs developing in Zipline before it will be of any use to us. For instance the endless looping through US holidays and opening and closing hours is really unnecessary for my purposes and in any event, if it has to be used, presumably one would need to add the like for each financial centre in which one trades.

In my existing software, either the data is there for the day and will be tested or it isn't and who cares.

FX support to trade non USD instruments from a USD or non USD base.

Dealing with automatically chucking out delisted stocks during a backtest.

The list goes on.

No doubt it can all be done...but it would be helpful to get past "go".

And once past "go" it would be nice if there wasn't the danger of each and every pull sending you back to jail and do not pass go.

**Comment by AnthonyFJGarner** [comment] 2015-10-31 15:13
Anyone tried Enthought Canopy? Does this improve the process for Windows?

**Comment by AnthonyFJGarner** [comment] 2015-10-31 20:57
Amusingly, looking through past issues here and also on the web in general, so many people have had frustrations trying to set up Zipline and many seem to give up the unequal struggle. It would be very helpful if the Quantopian team could give some very specific guidance.

Should we bother with Windows at all or will these problems simply come back and back to plague us as further changes are made here in github and  pulled down on our local git clients?

What do you guys recommend? Should we abandon Windows altogether and simply move to Linux? If we do, will it make this awful task any simpler or are we making yet another rod for our own backs and wasting our time?

If its feasible to use Windows, what package manager is going to be best? Are you aware that Pip in anaconda is incompatible with Zipline and yet updating Pip makes it impossible to load such dependencies as Logbook?

Is there no way you guys can provide a clear, simple, foolproof method to install Zipline in development mode and to keep it updated without the f***ups people are continually encountering?

Or should we forget Zipline altogether and move elsewhere?

Honestly guys, help us out here. Stay, go? Persevere? Stop wasting our time?

**Comment by elmq0022** [comment] 2015-10-31 22:48
Pip install has so far worked for me on windows. (Did not want 32 bit conda
and there is no 64 bit zipline build on binstar).

I would not pull from git directly if you need a stable build.

I would only use git if you are looking to develop / customize zipline
itself.

Also I would use a separate python environment via conda virtualenv for
zipline so you can freeze a stable  production environment.

Just my two cents and my experience.  I hope it's helpful.

**Comment by Zigguratti** [comment] 2015-11-01 01:38
Yep, I know what you mean.  To be fair, zipline are focused on the intraday
trading aspect where that level of detail (public holidays etc.) are quite
important.  But most people just start with a monthly back-tester and
indeed, I set that up my end without too much difficulty in python, but the
functionality should have been there ot begin with.  The public holiday
issue is a potential problem for non-US markets which, as you say, is
non-existent if you get your price data from bloomberg/factset (or probably
even yahoo!) the data is automatically absent on public holidays. Many
people just use back-test as of month-end as a sufficient approximation
with longer-term systematic backtests, but we are keen to have accurate
drawdowns etc. which requires daily data.  I got past go with zipline, but
it is painfully slow.  I believe there is a branch which speeds it up, but
its not in the core library yet.  I do think it is a great product and will
only get better however.  I have it working using historical sentiment data
to select stocks and re-weight every month, but that stopped working in
32-bit windows anaconda, hence I moved to ubuntu where it now works fine.
Another x-hours wasted re-installing everything and learning a new
environment ... I shall revisit in due-course, but just starting to build
our monthly backtester!

**Comment by mickeydonkey** [comment] 2015-11-01 05:30
Did anybody try the PyAlgoTrade before? It seems to be a well-documented backtest engine.

**Comment by michaeljohnbennett** [comment] 2015-11-03 11:37
The issue you are facing is what I think, but haven't confirmed is a bug/featurette with numpy and pandas in Windows.

There is a static piece of code introduced recently that translates an index of dates to longs (so SQLAlchemy can insert them as UTC timestamps). Unfortunately it borks (thats a real technical term) up in windoze and somehow returns back double the amount of values.

So if you have a some data with 2 dates, it would expect a list of 2 longs/ints back, however its getting 4.

https://github.com/quantopian/zipline/blob/master/zipline/assets/asset_writer.py

line 470

```python
    @staticmethod
    def dt_to_epoch_ns(dt_series):
        index = pd.to_datetime(dt_series.values)
        try:
            index = index.tz_localize('UTC')
        except TypeError:
            index = index.tz_convert('UTC')

        return index.view(int)

```

You could just revert back this block and I think it will work.

https://github.com/quantopian/zipline/commit/21366e8529f9df1f0348fd3bc43bd15e684a1085

@richafrank was the committer, perhaps he can give us some reason as to why it was introduced and was it tested on windows/conda? As its totally broken for me on conda 64 py 3.4 and all the pandas and numpy dependencies for zipline either installed via conda or via pip.

**Comment by AnthonyFJGarner** [comment] 2015-11-03 16:09
@richafrank I would be very interested to know whether this WAS tested on Windows/Conda. I had Zipline working without hitch up until this point.

**The real point is, if you guys tend to sideline testing on Windows/Conda then it would seem sensible for anyone with an interest in developing Zipline to move to linux. Presumably you use Linux?**

I would really appreciate some guidance here. Can you confirm that this error is indeed as a result of this commit?

I have spent 10 days installing and reinstalling anaconda and each and every one of the Zipline dependencies thinking that I had got something wrong. A good learning process no doubt but it would be pleasant not to have to repeat the process for future updates downloaded from the Zipline depositary.

**Comment by richafrank** [comment] 2015-11-03 16:21
Hi all,

Really sorry to hear how frustrating it is to run the latest zipline on windows. Even on a *nix environment, I've definitely found python and library installation can be a beast. The last time I tried getting all the zipline dependencies installed on windows, I found myself looking at the "Unofficial Windows Binaries for Python Extension Packages" (this was before wheels and before conda was 1.0).

In the past, we've built windows conda packages for each release, but as you mentioned @AnthonyFJGarner, the most recent conda release is missing all kinds of new features, and we haven't invested enough time to ensure master actually runs on windows. @michaeljohnbennett - Quantopian engineers are running OSX and linux, and Travis-CI is running linux, so windows is _not_ currently a part of our workflow or tests.  We're really reliant on and thankful for our community members helping out with windows issues, but as it currently stands, a move to linux would put you on a fully supported OS.

Regarding that particular [commit] (https://github.com/quantopian/zipline/commit/21366e8529f9df1f0348fd3bc43bd15e684a1085), the intent was to speed up the creation of the sqlite assets database, specifically the conversion of ~90K timestamps to ints, since the startup time in our hosted ipython environment had ballooned.  I don't have currently have a windows environment to confirm that commit is the cause.  That is quite the failure mode though - does anyone know if there's a known issue with pandas?

**Comment by richafrank** [comment] 2015-11-03 19:36
Could someone try out https://github.com/quantopian/zipline/commit/d4fc1ac3022b7b5ed84c1b622707f91f132cf1a9 to see if it fixes this?  (The suggestion came from @llllllllll .)

**Comment by easytrader** [comment] 2015-11-04 01:09
I have tried the specific commit "Perf tracker refactor on lazy #745 opened on 2 Oct by ehebert"
But When I  python setup.py install the zipline, it will show the error "AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'" . Does anyone know which specific commit can install normally.
Thank you very much.

**Comment by michaeljohnbennett** [comment] 2015-11-04 02:51
You have a compiler error further up the page, most likely scipy or
something hasn't compiled properly.

Try installing the conda packages for the zipline dependencies where you
can, this stops the compiler issues, otherwise you will need visual studio
2010 installed with c++ compilers. If you are on python 3.4

**Comment by michaeljohnbennett** [comment] 2015-11-04 11:04
I did a simple test and that solves it for me here on a windows 10 install.

```python
import pandas as pd
import numpy as np
date_1 = pd.Timestamp('2013-01-01', tz='UTC')
date_2 = pd.Timestamp('2013-02-01', tz='UTC')
test_series = pd.Series(data=[date_1, date_2])

pd.to_datetime(test_series.values).view(np.int64)
```
looks good:
```python
array([1356998400000000000, 1359676800000000000], dtype=int64)
```
compared to:
```python
pd.to_datetime(test_series.values).view(int)
array([ -389677056,   315950810, -2125004800,   316574424])
```

Can someone push that commit to master please?

**Comment by richafrank** [comment] 2015-11-04 13:51
> I did a simple test and that solves it for me here on a windows 10 install.

Awesome, seems like an issue not specific to windows but to 32-bit, and many folks are running 32-bit conda on windows.

Merged to master with https://github.com/quantopian/zipline/commit/1377d25c9534d3ba72f1a622c5f99607526f3520.

I also opened a separate issue for @easytrader 's error: https://github.com/quantopian/zipline/issues/814.

**Closed by richafrank** 2015-11-04 13:51 UTC
