### ISSUE TITLE
Error In Simulated Source

### ISSUE THREAD

**Issue by smtoycom** [quantopian/zipline#851] opened 2015-11-17 05:51 UTC
I have tried using simulated source (zipline.sources.simulated) in the buyapple.py example, got error as below:

 File "C:\Python34\lib\site-packages\zipline\finance\risk\period.py", line 262,
 in calculate_beta
    eigen_values = la.eigvals(C)
  File "C:\Python34\lib\site-packages\numpy\linalg\linalg.py", line 888, in eigv
als
    _assertFinite(a)
  File "C:\Python34\lib\site-packages\numpy\linalg\linalg.py", line 217, in _ass
ertFinite
    raise LinAlgError("Array must not contain infs or NaNs")
numpy.linalg.linalg.LinAlgError: Array must not contain infs or NaNs

To reproduce the bugs, use the simulated source and set the end date to any future date.

**Comment by richafrank** [comment] 2015-11-17 15:51
Hi @smtoycom .  Looks like the same symptom as #151.  I think the cause here is that there are missing benchmark prices for those dates in the future.  This introduces `NaN`s into the benchmark and algo returns arrays, from which zipline calculates the beta.  Would you want `NaN` beta instead of the exception?

**Comment by smtoycom** [comment] 2015-11-18 02:11
Hi @richafrank Thanks for your reply. Please advise how to return NaN beta or set zero for all data for future benchmark.

**Comment by richafrank** [comment] 2015-11-18 15:45
I think https://github.com/quantopian/zipline/commit/bb43337b2a4821b58a368551e044a8e8f31b7010 will prevent the error, but I'm not sure if the values returned are useful to you.  @twiecki Do you have any thoughts on the proper handling for missing benchmark data?  Is the linked workaround a good idea?

**Comment by twiecki** [comment] 2015-11-18 15:52
Technically, beta should be `nan` in that case. Not sure if that causes problems downstream though.

**Comment by richafrank** [comment] 2015-11-18 16:32
Aha, do you think https://github.com/quantopian/zipline/blob/bb43337b2a4821b58a368551e044a8e8f31b7010/zipline/finance/risk/period.py#L257 should be `nan` as well, or just the missing benchmark case?  I'll run tests to see the downstream impact...

**Comment by twiecki** [comment] 2015-11-18 16:46
That should be nan too, yeah.

**Comment by richafrank** [comment] 2015-11-19 18:12
Closing with #859

**Closed by richafrank** 2015-11-19 18:12 UTC
