### ISSUE TITLE
Ingest custom data as a CSV file

### ISSUE THREAD

**Issue by niklay14** [quantopian/zipline#2162] opened 2018-05-01 19:38 UTC
Dear Zipline Maintainers,
I have some equity price data (CSV file) in the OHLCV + Dividends + Splits format and tried to ingest the data using `zipline ingest -b bundle_name`. However, I always get the following error code:

```
Traceback (most recent call last):
  File "/Users/niklasamslgruber/anaconda3/envs/py35/bin/zipline", line 11, in <module>
    sys.exit(main())
  File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/zipline/__main__.py", line 331, in ingest
    show_progress,
  File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/zipline/data/bundles/core.py", line 451, in ingest
    pth.data_path([name, timestr], environ=environ),
  File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/zipline/data/bundles/csvdir.py", line 94, in ingest
    self.csvdir)
  File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/zipline/data/bundles/csvdir.py", line 120, in csvdir_bundle
    raise ValueError("%s is not a directory" % csvdir)
ValueError: /Users/niklasamslgruber/Desktop/Daedalus/csvdir/daily/WCH_01.05.18_21.25.csv is not a directory

```

I registered the bundle in the .zipline/extension.py file:

```
import pandas as pd
from zipline.data.bundles import register
from zipline.data.bundles.csvdir import csvdir_equities

start_session = pd.Timestamp('2017-1-1', tz='utc')
end_session = pd.Timestamp('2017-12-31', tz='utc')

register(
    'custom1',
    csvdir_equities(
        ['daily'],
        "/Users/niklasamslgruber/Desktop/Daedalus/csvdir/daily/WCH_01.05.18_21.25.csv"))

```

I hope you can help me!

Sincerely,
Niklas

**Comment by freddiev4** [comment] 2018-05-01 19:43
Your directory to your daily data should be:

```
"/Users/niklasamslgruber/Desktop/Daedalus/csvdir"
```

**Comment by niklay14** [comment] 2018-05-01 19:45
I still get the same error:

`ValueError: /Users/niklasamslgruber/Desktop/Daedalus/csvdir/WCH_01.05.18_21.25.csv is not a directory`

**Comment by freddiev4** [comment] 2018-05-01 19:57
Hmm.. not sure why it would be looking at your csv file to check if it's a directory.

This is what my custom bundle looks like right now:

```
register(
    'custom-csvdir-bundle',
    csvdir_equities(
        ["daily"],
        '/Users/freddiev4/Documents/csvdir'
    ),
    calendar_name='TFS',
    start_session=start_session,
    end_session=end_session
)
```

**Comment by niklay14** [comment] 2018-05-01 20:00
Changed that and not get this error:

```
Traceback (most recent call last):
  File "/Users/niklasamslgruber/anaconda3/envs/py35/bin/zipline", line 11, in <module>
    sys.exit(main())
  File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/zipline/__main__.py", line 331, in ingest
    show_progress,
  File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/zipline/data/bundles/core.py", line 400, in ingest
    end_session,
  File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/zipline/data/us_equity_pricing.py", line 201, in __init__
    "Start session %s is invalid!" % start_session
ValueError: Start session 2017-01-01 00:00:00+00:00 is invalid!
```

The CSV looks like that:

```
Date,Open,High,Low,Close,Volume,Dividend,Split
2017-01-02,98.84,101.15,98.5,100.2,63638.0,0,0
2017-01-03,100.45,103.2,100.35,102.7,146035.0,0,0
2017-01-04,102.7,102.95,100.9,101.75,114505.0,0,0
2017-01-05,101.6,102.35,101.25,102.0,80067.0,0,0
```

**Comment by freddiev4** [comment] 2018-05-01 20:14
Is it fair to guess that, based off your [WCH](https://finance.yahoo.com/quote/wch.de/) csv and your location, you're looking at German stocks?

If that's the case, then that means there are probably dates in your `csv` file where stocks won't line up with the `NYSE` calendar, which is the default calendar. If that's the case, you're going to want to look into building your own [Trading Calendar](http://www.zipline.io/trading-calendars.html).

**Comment by niklay14** [comment] 2018-05-01 20:26
Yes, I'm using german stocks. I just downloaded the data for AAPL from Yahoo Finance and the error still exists

**Comment by freddiev4** [comment] 2018-05-01 20:31
What happens if you change your `start_session` to `'2017-1-2'

**Comment by niklay14** [comment] 2018-05-01 20:36
Then I get the first error again:

`ValueError: /Users/niklasamslgruber/Desktop/Daedalus/csvdir/AAPL.csv is not a directory`

**Comment by freddiev4** [comment] 2018-05-01 20:37
Can you post the first 5 or 10 rows of the `AAPL.csv`?  I'm going to try and reproduce this

**Comment by niklay14** [comment] 2018-05-01 20:41
```
Date;Open;High;Low;Close;Volume;Dividend;Split
2017-01-03;115.800003;116.330002;114.760002;116.150002;28781900;0;0
2017-01-04;115.849998;116.510002;115.750000;116.019997;21118100;0;0
2017-01-05;115.919998;116.860001;115.809998;116.610001;22193600;0;0
2017-01-06;116.779999;118.160004;116.470001;117.910004;31751900;0;0
2017-01-09;117.949997;119.430000;117.940002;118.989998;33561900;0;0
2017-01-10;118.769997;119.379997;118.300003;119.110001;24462100;0;0
2017-01-11;118.739998;119.930000;118.599998;119.750000;27588600;0;0
2017-01-12;118.900002;119.300003;118.209999;119.250000;27086200;0;0
2017-01-13;119.110001;119.620003;118.809998;119.040001;26111900;0;0
2017-01-17;118.339996;120.239998;118.220001;120.000000;34439800;0;0
```

**Comment by freddiev4** [comment] 2018-05-01 20:59
So I was able to reproduce the `start-session` error, but not the `ValueError`.

Here's my setup:

My `AAPL.csv` file is located in: `'/Users/freddiev4/Documents/csvdir/daily/`

My `~/.zipline/extensions.py`
```
import pandas as pd
from zipline.data.bundles import register
from zipline.data.bundles.csvdir import csvdir_equities

start_session = pd.Timestamp('2017-1-3', tz='utc')
end_session = pd.Timestamp('2017-1-17', tz='utc')

register(
    'niklas-bundle',
    csvdir_equities(
        ["daily"],
        '/Users/freddiev4/Documents/csvdir'
    ),
    start_session=start_session,
    end_session=end_session
)
```
Some things to keep in mind:

- The `start_session` date needs to be aligned with the first date that appears in the `csv` file
- The names of the columns need to all be lowercase (should probably just open a PR for `csvdir` to ignore letter cases)

**Comment by freddiev4** [comment] 2018-05-01 21:05
Edit to comment above:
> The names of the columns need to all be lowercase (should probably just open a PR for csvdir to ignore letter cases)

The error I saw actually comes from `us_equity_pricing.py` / pandas:
```
 File "/Users/freddiev4/Documents/quantopian/zipline/zipline/data/us_equity_pricing.py", line 251, in <genexpr>
    for sid, df in data
  File "/Users/freddiev4/Documents/quantopian/zipline/zipline/data/us_equity_pricing.py", line 416, in to_ctable
    # we already have a ctable so do nothing
  File "/Users/freddiev4/Documents/quantopian/zipline/zipline/data/us_equity_pricing.py", line 419, in to_ctable
    winsorise_uint32(raw_data, invalid_data_behavior, 'volume', *OHLC)
  File "/Users/freddiev4/Documents/quantopian/zipline/zipline/data/us_equity_pricing.py", line 121, in winsorise_uint32
    
  File "/Users/freddiev4/Documents/quantopian/zipline/zipline/data/us_equity_pricing.py", line 137, in winsorise_uint32
    mask = df[columns] > UINT32_MAX
```
.
.
.
```
    indexer = self.ix._convert_to_indexer(key, axis=1)
  File "/Users/freddiev4/.virtualenvs/zip35/lib/python3.5/site-packages/pandas/core/indexing.py", line 1214, in _convert_to_indexer
    raise KeyError('%s not in index' % objarr[mask])
KeyError: "['volume' 'open' 'high' 'close' 'low'] not in index"
```

**Comment by freddiev4** [comment] 2018-05-01 21:12
Let me know if you get it to work (based off my https://github.com/quantopian/zipline/issues/2162#issuecomment-385788553)

**Comment by niklay14** [comment] 2018-05-01 21:17
So I changed everything (CSV with lowercases and comma-separated, etc.), but I still get this ValueError
```

 File "/Users/niklasamslgruber/anaconda3/envs/py35/bin/zipline", line 11, in <module>
    sys.exit(main())
  File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/zipline/__main__.py", line 331, in ingest
    show_progress,
  File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/zipline/data/bundles/core.py", line 451, in ingest
    pth.data_path([name, timestr], environ=environ),
  File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/zipline/data/bundles/csvdir.py", line 94, in ingest
    self.csvdir)
  File "/Users/niklasamslgruber/anaconda3/envs/py35/lib/python3.5/site-packages/zipline/data/bundles/csvdir.py", line 120, in csvdir_bundle
    raise ValueError("%s is not a directory" % csvdir)
ValueError: /Users/niklasamslgruber/Desktop/Daedalus/csvdir/daily/AAPL.csv is not a directory

```

**Comment by niklay14** [comment] 2018-05-01 21:41
I don't get any errors now, I wrote the wrong path into the register function. However, I tried to run the double crossover example with apple and the data doesn't see to be available. How can I use the data from this bundle with the run_algorithm function.

**Comment by niklay14** [comment] 2018-05-02 10:50
The error is fixed, however I cannot use the data while running run_algorithm. I always get this error: zipline.errors.SymbolNotFound: Symbol 'AAPL' was not found. Do I need to tell zipline that the data in the CSV file is the apple price data or how can I solve this error?

**Comment by freddiev4** [comment] 2018-05-04 00:33
Just getting to your next question (https://github.com/quantopian/zipline/issues/2172) now. Closing this issue as we solved your other problem.

**Closed by freddiev4** 2018-05-04 00:33 UTC
Labels: Data Bundle

**Comment by bhushanjawle** [comment] 2019-10-18 10:26
Greetings,  
I see this issue is closed but found this when I got same error for ingesting data for Indian stocks.
Error and source is exactly same as mentioned in https://github.com/quantopian/zipline/issues/2162#issuecomment-385790239.
Can  you please point me to what else I can try to resolve this issue ?

**Comment by bhushanjawle** [comment] 2019-10-21 11:13
Hi @freddiev4 , Is it recommended I open a fresh issue for this. Please let me know

**Comment by sivasunku** [comment] 2019-11-08 15:02
Hello bhushanjawle,
I hope the issue might have got resolved. But just in case,check the 'csv' file. Probably the column names would have Upper case letters. Make all these OHLCV columns to lower case and try.. it should fix.

**Comment by bhushanjawle** [comment] 2020-09-12 13:31
Thank you. That didn't work, moved over to alternative way to backrest.

**Comment by nandonachi** [comment] 2021-02-21 16:27
Im facing a similar issue 

`Error: No bundle registered with the name 'test-csvdir-bundle'
`

Env details

```
conda list:

zipline                   1.4.1               np114py36_0    quantopian
python                    3.6.12               h5500b2f_2
pandas                    1.1.5                    pypi_0    pypi
zipline                   1.4.1               np114py36_0    quantopian

Using Windows 10
```

Im tryng to ingest ABBOTINDIANS.csv, stock in India

![image](https://user-images.githubusercontent.com/1931122/108631135-8d50e880-748e-11eb-94cc-e0851bfbb59d.png)

extension.py
```
# necessary imports
import pandas as pd
from zipline.data.bundles import register
from zipline.data.bundles.csvdir import csvdir_equities


start_session = pd.Timestamp('2017-9-1', tz='utc')
end_session = pd.Timestamp('2018-9-12', tz='utc')


register(
    'nse_stock_data',
    csvdir_equities(
        ['daily'], 
        r'C:\Users\<username>\OneDrive\Stock\Stock_data_2',
        ),
    calendar_name='XBOM',
    start_session=start_session,
    end_session=end_session
)
```

TIA!
