### ISSUE TITLE
conflict between 32-bit python 3.5 and zipline

### ISSUE THREAD

**Issue by lxlarcher** [quantopian/zipline#1896] opened 2017-07-29 02:10 UTC
Dear Zipline Maintainers,
when i try to download the zipline by conda, it shows the zipline work under python2.7 version, so how it work under python 3.5 version？

Sincerely,
Archer Liu

**Comment by FreddieV4** [comment] 2017-07-29 04:46
Hi Archer. Is your question more about how a python package can be used in both Python 2 and 3?

Based off the title of your issue it sounded like you have trouble getting zipline to work with Python 3.5, so just wanted to get some clarification first :)

**Comment by llllllllll** [comment] 2017-07-29 06:50
The issue is that we have not published conda packages for python 3.5 so conda cannot resolve zipline. Right now you can install zipline in a Python 3.4 conda environment if you need Python 3.

**Comment by lxlarcher** [comment] 2017-07-29 07:54
all right, thank u so much, maybe I will wait for the conda packages for python 3.5.


发自网易邮箱大师
在2017年07月29日 14:51，Joe Jevnik 写道:

The issue is that we have not published conda packages for python 3.5 so conda cannot resolve zipline. Right now you can install zipline in a Python 3.4 conda environment if you need Python 3.

**Comment by lxlarcher** [comment] 2017-07-29 10:00
Hi Freddie, I mean I had trouble getting zip line to work with python3.5. Now, I figure out zipline only work for python2.x or python3.4.   Thanks .


发自网易邮箱大师
在2017年07月29日 12:46，Freddie Vargus 写道:

Hi Archer. Is your question more about how a python package can be used in both Python 2 and 3?

Based off the title of your issue it sounded like you have trouble getting zipline to work with Python 3.5, so just wanted to get some clarification first :)

**Comment by FreddieV4** [comment] 2017-07-29 18:00
Hi @lxlarcher you can also run `pip install zipline` without conda and it should still work with Python 3.5

**Comment by lxlarcher** [comment] 2017-07-30 01:41
Wonderful ,thank you so much. 


发自网易邮箱大师
在2017年07月30日 02:00，Freddie Vargus 写道:

Hi @lxlarcher you can also run pip install zipline without conda and it should still work with Python 3.5

**Comment by RJUNS** [comment] 2017-07-30 18:29
Am not able to install zipline on python 3.5 the error is:
 
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

  ----------------------------------------
  Failed building wheel for cyordereddict
  Failed building wheel for bcolz
  Failed building wheel for lru-dict
And i have already installed visual studio 14.10 build tools (in control panel it shows, Microsoft Visual Studio 2017) before installing zipline, any guesses why its unable to work?

**Comment by FreddieV4** [comment] 2017-07-30 20:27
Hi @RJUNS if you're trying to run `pip install zipline` for Windows, then I'm not entirely sure right now how to deal with that particular issue. I'll look more into it.

We currently have conda packages for Python 3.5 on Windows, so you can install using `conda`.

There's more information in the [Install Guide](http://www.zipline.io/install.html) as well.

**Comment by RJUNS** [comment] 2017-07-31 06:45
Hey @FreddieV4 , i tried installing using conda, but i got the following error:
D:\Folders\ArJuN\>activate py35

(py35) D:\Folders\ArJuN\>conda install zipline
Fetching package metadata .............

PackageNotFoundError: Package missing in current win-32 channels:
  - zipline

(py35) D:\Folders\ArJuN\>conda install -c Quantopian zipline
Fetching package metadata ...............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.5*
  - zipline -> logbook -> python 2.7*
Use "conda info <package>" to see the dependencies for each package.

And i tried installing zipline through local path by downloading zipline from github , but it throws error  while installing as described in my previous comment.

Am using virtual env, and am on windows 7 32 bit machine, is it compatible with 32 bit machine? however i was able to run zipline when i had python 3.4. but facing problem with python 3.5.

**Comment by FreddieV4** [comment] 2017-07-31 14:39
@RJUNS We don't have builds/support for Windows-32 bit so your best bet is to install on a 64-bit machine I believe. 

If your hardware supports 64-bit then you could run a 64-bit VM I think too

**Comment by RJUNS** [comment] 2017-07-31 14:47
Oh, then i will better stick with python 3.4, as it supports my 32-bit somehow, thanks for help anyways @FreddieV4 :)

**Comment by FreddieV4** [comment] 2017-08-08 15:26
Hi @RJUNS  I'm going to go ahead and close this issue. Feel free to re-open it if you have other issues with this

**Closed by FreddieV4** 2017-08-08 15:26 UTC
Labels: 32-bit, Install Help
