### ISSUE TITLE
Web call dependency - Benchmarks,py

### ISSUE THREAD

**Issue by AndreasClenow** [quantopian/zipline#2445] opened 2019-03-19 12:28 UTC
While having an internet outage, I noticed that Zipline cannot run a backtest without internet data, due to dependency in benchmarks.py.

I am unsure why a request for the history of SPY would be needed to run the backtest. The dependency means that without modification of the code, it is not possible to run a local backtest with local data without an internet connection. 

I suggest to either remove this http call, if not required for anything vital, or add error handling so that a backtest can proceed even if this call fails.

`ConnectionError: HTTPSConnectionPool(host='api.iextrading.com', port=443): Max retries exceeded with url: /1.0/stock/SPY/chart/5y (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000002742EFB9828>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))`

**Code in question, from benchmarks.py**
```
def get_benchmark_returns(symbol):
    """
    Get a Series of benchmark returns from IEX associated with `symbol`.
    Default is `SPY`.

    Parameters
    ----------
    symbol : str
        Benchmark symbol for which we're getting the returns.

    The data is provided by IEX (https://iextrading.com/), and we can
    get up to 5 years worth of data.
    """
    r = requests.get(
        'https://api.iextrading.com/1.0/stock/{}/chart/5y'.format(symbol)
    )
    data = r.json()

    df = pd.DataFrame(data)

    df.index = pd.DatetimeIndex(df['date'])
    df = df['close']

    return df.sort_index().tz_localize('UTC').pct_change(1).iloc[1:]
```

**Comment by RichardDale** [comment] 2019-08-06 04:06
Agreed - there should be no need to online during a backtest at all.  And now that IEX functionality has changed, this routine is even more broken.

For even more utility, it should be just reference a given symbol inside the bundle.  No symbol exists = no benchmark returns.

**Comment by ssanderson** [comment] 2020-01-22 21:34
I'm going through and consolidating benchmark-related issues. Closing this as a dupe of https://github.com/quantopian/zipline/issues/2627. If there are important notes in here that I've missed in that issue, feel free to add them in that thread.

**Closed by ssanderson** 2020-01-22 21:34 UTC
Labels: Benchmark

**Comment by cemal95** [comment] 2020-05-01 02:19
Maybe make sure that when you have connection, that the data gets stored, so that when there is no internet connection it goes to local data and whenever there is a connection the program can retrieve latest data and run normally using the api
