### ISSUE TITLE
sample example not working

### ISSUE THREAD

**Issue by chaowu2009** [quantopian/zipline#989] opened 2016-02-10 21:13 UTC
**cml**: python run_algo.py -f dual_moving_average.py --symbols AAPL --start 2011-1-1 --end 2012-1-1

**Error**: Couldn't import dot_parser, loading of dot files will not be possible

solved by the following procedure:
pip uninstall pyparsing
pip install -Iv https://pypi.python.org/packages/source/p/pyparsing/pyparsing-1.5.7.tar.gz#md5=9be0fcdcc595199c646ab317c1d9a709
pip install pydot

**Comment by llllllllll** [comment] 2016-02-24 18:51
Which version of zipline do you have? Did you modify the example in any way? I am surprised that either of those packages would cause this behavior because I do not have them installed in either my python 2 or 3 virtualenvs for zipline.

Can you reproduce this in a new virtual environment with only zipline installed?

**Comment by FreddieV4** [comment] 2017-05-22 20:14
I'm going to close this because of the recently merged https://github.com/quantopian/zipline/pull/1707, as that example was not previously working because it had used code from deprecated API calls.

**Closed by FreddieV4** 2017-05-22 20:14 UTC
Labels: Bug, Documentation
